export const config = {
  PUBLIC_URL: 'http://localhost:3000',
  REACT_APP_BASENAME: '',
  REACT_APP_ID_ENDPOINT: 'https://preview.assureid.acuant.net',
  REACT_APP_FRM_ENDPOINT: 'https://preview.face.acuant.net',
  REACT_APP_MEDICSCAN_ENDPOINT: 'https://medicscan.acuant.net',
  REACT_APP_LIVENESS_ENDPOINT: 'https://preview.passlive.acuant.net',
  REACT_APP_USER_NAME: 'acuantgo',
  REACT_APP_PASSWORD: 'PB6HemyWr!w$X',
  REACT_APP_FRM_ENABLED: true,
  REACT_APP_GLARE_METRIC_ENABLED: false,
  REACT_APP_SHARPNESS_METRIC_ENABLED: true,
  REACT_APP_IDPASSPORT_ENABLED: true,
  REACT_APP_MEDICAL_CARD_ENABLED: true,
  REACT_APP_MOBILE_ONLY: true,
  REACT_APP_SUBSCRIPTION_ID: 'b15c1ca3-e673-4971-a415-e77e109cbc2b',
  REACT_APP_SENTRY_SUBSCRIPTION_ID: '',
  NODE_ENV: 'development',
};
